<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7zSeT07\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7zSeT07/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7zSeT07.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7zSeT07\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7zSeT07\App_KernelDevDebugContainer([
    'container.build_hash' => '7zSeT07',
    'container.build_id' => 'b18b56bc',
    'container.build_time' => 1659966999,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7zSeT07');
